# Generated by Django 5.0.2 on 2024-03-23 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_service_category_alter_service_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='attachments',
        ),
        migrations.AddField(
            model_name='task',
            name='image',
            field=models.ImageField(blank=True, default='default_task_image.jpg', null=True, upload_to='task_images/'),
        ),
    ]
