# Generated by Django 5.0.2 on 2024-03-23 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_remove_task_attachments_task_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='image',
            field=models.ImageField(blank=True, default='no_image.jpg', null=True, upload_to='task_images/'),
        ),
    ]
