# Generated by Django 5.0.2 on 2024-03-21 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='phone_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(upload_to='attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.task')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='attachments',
            field=models.ManyToManyField(blank=True, related_name='attachments', to='profiles.attachment'),
        ),
    ]
